
/*Generated by Informatica Data Replication Console */
/*Converting DDL from Sybase ASE to MS SQL Server*/
CREATE TABLE [ddl].[dbo].[SBS_Basic_Types]
(s_int int NOT NULL/*Sybase ASE datatype: INT(0, 0)*/,
s_bit bit NOT NULL/*Sybase ASE datatype: BIT(0, 0)*/,
s_tinyint tinyint/*Sybase ASE datatype: TINYINT(0, 0)*/,
s_smallint smallint/*Sybase ASE datatype: SMALLINT(0, 0)*/,
s_usmallint smallint/*Sybase ASE datatype: USMALLINT(0, 0)*/,
s_uint int/*Sybase ASE datatype: UINT(0, 0)*/,
s_bigint bigint/*Sybase ASE datatype: BIGINT(0, 0)*/,
s_ubigint bigint/*Sybase ASE datatype: UBIGINT(0, 0)*/,
PRIMARY KEY (s_int)
);

CREATE TABLE [ddl1].[dbo].[SBS_Bigdate_Types]
(s_int int NOT NULL/*Sybase ASE datatype: INT(0, 0)*/,
s_bigtime time/*Sybase ASE datatype: BIGTIME(0, 6)*/,
s_bigdatetime datetime2/*Sybase ASE datatype: BIGDATETIME(0, 6)*/,
PRIMARY KEY (s_int)
);

CREATE TABLE [ddl].[dbo].[SBS_Binary_Types]
(s_int int NOT NULL/*Sybase ASE datatype: INT(0, 0)*/,
s_binary binary(1000)/*Sybase ASE datatype: BINARY(0, 0)*/,
s_varbinary varbinary(1000)/*Sybase ASE datatype: VARBINARY(0, 0)*/,
s_image image/*Sybase ASE datatype: IMAGE(0, 0)*/,
PRIMARY KEY (s_int)
);

CREATE TABLE [ddl].[dbo].[SBS_Character_Types]
(s_int int NOT NULL/*Sybase ASE datatype: INT(0, 0)*/,
s_char char(100)/*Sybase ASE datatype: CHAR(0, 0)*/,
s_varchar varchar(500)/*Sybase ASE datatype: VARCHAR(0, 0)*/,
s_unichar nchar(200)/*Sybase ASE datatype: UNICHAR(0, 0)*/,
s_univarchar nvarchar(1000)/*Sybase ASE datatype: UNIVARCHAR(0, 0)*/,
s_nchar nchar(100)/*Sybase ASE datatype: NCHAR(0, 0)*/,
s_nvarchar nvarchar(500)/*Sybase ASE datatype: NVARCHAR(0, 0)*/,
PRIMARY KEY (s_int)
);

CREATE TABLE [ddl].[dbo].[SBS_Character_Types_lng]
(s_int int NOT NULL/*Sybase ASE datatype: INT(0, 0)*/,
s_text text/*Sybase ASE datatype: TEXT(0, 0)*/,
s_unitext ntext/*Sybase ASE datatype: UNITEXT(0, 0)*/,
PRIMARY KEY (s_int)
);

CREATE TABLE [ddl].[dbo].[SBS_Datetime_Types]
(s_int int NOT NULL/*Sybase ASE datatype: INT(0, 0)*/,
s_smalldatetime smalldatetime/*Sybase ASE datatype: SMALLDATETIME(0, 0)*/,
s_datetime datetime/*Sybase ASE datatype: DATETIME(0, 3)*/,
s_date date/*Sybase ASE datatype: DATE(0, 0)*/,
s_time time/*Sybase ASE datatype: TIME(0, 3)*/,
PRIMARY KEY (s_int)
);

CREATE TABLE [ddl].[dbo].[SBS_Decimal_Types]
(s_int int NOT NULL/*Sybase ASE datatype: INT(0, 0)*/,
s_numeric numeric(38, 8)/*Sybase ASE datatype: NUMERIC(38, 8)*/,
s_decimal decimal(38, 8)/*Sybase ASE datatype: DECIMAL(38, 8)*/,
s_float FLOAT(32)/*Sybase ASE datatype: FLOAT(0, 0)*/,
s_double FLOAT(32)/*Sybase ASE datatype: FLOAT(0, 0)*/,
s_real real/*Sybase ASE datatype: REAL(0, 0)*/,
PRIMARY KEY (s_int)
);

CREATE TABLE [ddl].[dbo].[SBS_Money_Types]
(s_int int NOT NULL/*Sybase ASE datatype: INT(0, 0)*/,
s_smallmoney smallmoney/*Sybase ASE datatype: SMALLMONEY(0, 0)*/,
s_money money/*Sybase ASE datatype: MONEY(0, 0)*/,
PRIMARY KEY (s_int)
);


