ALTER TABLE O2D_DDL_3.O2D_DDL_3_NUMBERTYPES ADD CONSTRAINT O2D_DDL_3_CHK_1 CHECK (S_PK_FORMAPPING>0);
ALTER TABLE O2D_DDL_3.O2D_DDL_3_CHARTYPES ADD CONSTRAINT O2D_DDL_3_CHK_2 CHECK (S_PK_FORMAPPING>0);
ALTER TABLE O2D_DDL_3.O2D_DDL_3_DATATYPES ADD CONSTRAINT O2D_DDL_3_CHK_3 CHECK (S_PK_FORMAPPING>0);
ALTER TABLE O2D_DDL_3.O2D_DDL_3_RAWLOBTYPES ADD CONSTRAINT O2D_DDL_3_CHK_4 CHECK (S_PK_FORMAPPING>0);
commit;
