CREATE INDEX O2D_DDL_3_INDEX_1 ON O2D_DDL_3.O2D_DDL_3_NUMBERTYPES (S_INTEGER);
CREATE INDEX O2D_DDL_3_INDEX_2 ON O2D_DDL_3.O2D_DDL_3_CHARTYPES (S_CHAR_MAX);
CREATE INDEX O2D_DDL_3_INDEX_3 ON O2D_DDL_3.O2D_DDL_3_DATATYPES (S_DATE);
CREATE INDEX O2D_DDL_3_INDEX_4 ON O2D_DDL_3.O2D_DDL_3_RAWLOBTYPES (S_RAW_MAX);
commit;
