ALTER TABLE O2D_DDL_3.O2D_DDL_3_NUMBERTYPES ADD add ( S_PK_FORMAPPING INTEGER ) add constraint primary key (S_PK_FORMAPPING);
ALTER TABLE O2D_DDL_3.O2D_DDL_3_CHARTYPES ADD add ( S_PK_FORMAPPING INTEGER ) add constraint primary key (S_PK_FORMAPPING);
ALTER TABLE O2D_DDL_3.O2D_DDL_3_DATATYPES ADD add ( S_PK_FORMAPPING INTEGER ) add constraint primary key (S_PK_FORMAPPING);
ALTER TABLE O2D_DDL_3.O2D_DDL_3_RAWLOBTYPES ADD add ( S_PK_FORMAPPING INTEGER ) add constraint primary key (S_PK_FORMAPPING);
commit;
/*
ALTER TABLE O2D_DDL_3.O2D_DDL_3_NUMBERTYPES ADD CONSTRAINT O2D_DDL_3_1_PK PRIMARY KEY (S_PK_FORMAPPING);
ALTER TABLE O2D_DDL_3.O2D_DDL_3_CHARTYPES ADD CONSTRAINT O2D_DDL_3_2_PK PRIMARY KEY (S_PK_FORMAPPING);
ALTER TABLE O2D_DDL_3.O2D_DDL_3_DATATYPES ADD CONSTRAINT O2D_DDL_3_3_PK PRIMARY KEY (S_PK_FORMAPPING);
ALTER TABLE O2D_DDL_3.O2D_DDL_3_RAWLOBTYPES ADD CONSTRAINT O2D_DDL_3_4_PK PRIMARY KEY (S_PK_FORMAPPING);
commit;
*/
