--oracle
--DROP USER O2D_DDL_3 CASCADE;
CREATE USER O2D_DDL_3 IDENTIFIED BY O2D_DDL_3;
GRANT CONNECT, RESOURCE TO O2D_DDL_3;

--db2
CONNECT TO SOURCE;
CREATE SCHEMA O2D_DDL_3 AUTHORIZATION ATF;
CONNECT RESET;
