ALTER TABLE O2D_DDL_3.O2D_DDL_3_NUMBERTYPES DROP CONSTRAINT O2D_DDL_3_CHK_1;
ALTER TABLE O2D_DDL_3.O2D_DDL_3_CHARTYPES DROP CONSTRAINT O2D_DDL_3_CHK_2;
ALTER TABLE O2D_DDL_3.O2D_DDL_3_DATATYPES DROP CONSTRAINT O2D_DDL_3_CHK_3;
ALTER TABLE O2D_DDL_3.O2D_DDL_3_RAWLOBTYPES DROP CONSTRAINT O2D_DDL_3_CHK_4;
commit;
