ALTER TABLE O2D_DDL_3.O2D_DDL_3_NUMBERTYPES DROP ( S_PK_FORMAPPING  );
ALTER TABLE O2D_DDL_3.O2D_DDL_3_CHARTYPES DROP ( S_PK_FORMAPPING  );
ALTER TABLE O2D_DDL_3.O2D_DDL_3_DATATYPES DROP ( S_PK_FORMAPPING  );
ALTER TABLE O2D_DDL_3.O2D_DDL_3_RAWLOBTYPES DROP ( S_PK_FORMAPPING  );
commit;
