CREATE TABLE O2D_DDL_4.O2D_DDL_4_FOR_MAPPING
(
  S_INTEGER                 NUMBER(38,10),
  S_VARCHAR2		    VARCHAR2(2000 BYTE),
  S_PK_FORMAPPING	    INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE O2D_DDL_4.O2D_DDL_4_FOR_MAPPING ADD (
  CONSTRAINT O2D_DDL_4_FOR_MAPPING_PK
 PRIMARY KEY
 (S_PK_FORMAPPING));
 
ALTER TABLE O2D_DDL_4.O2D_DDL_4_FOR_MAPPING ADD SUPPLEMENTAL LOG GROUP O2D_DDL_4_0_LG (S_PK_FORMAPPING) ALWAYS;
commit;
