CREATE TABLE O2D_DDL_4.O2D_DDL_4_NUMBERTYPES_NEW AS (SELECT * FROM O2D_DDL_4.O2D_DDL_4_NUMBERTYPES);
CREATE TABLE O2D_DDL_4.O2D_DDL_4_CHARTYPES_NEW AS (SELECT * FROM O2D_DDL_4.O2D_DDL_4_CHARTYPES);
CREATE TABLE O2D_DDL_4.O2D_DDL_4_DATATYPES_NEW AS (SELECT * FROM O2D_DDL_4.O2D_DDL_4_DATATYPES);
CREATE TABLE O2D_DDL_4.O2D_DDL_4_RAWLOBTYPES_NEW AS (SELECT * FROM O2D_DDL_4.O2D_DDL_4_RAWLOBTYPES);
commit;
