drop table O2D_DDL_4.O2D_DDL_4_NUMBERTYPES;
drop table O2D_DDL_4.O2D_DDL_4_CHARTYPES;
drop table O2D_DDL_4.O2D_DDL_4_DATATYPES; 
drop table O2D_DDL_4.O2D_DDL_4_RAWLOBTYPES;
drop table O2D_DDL_4.O2D_DDL_4_NUMBERTYPES_NEW;
drop table O2D_DDL_4.O2D_DDL_4_CHARTYPES_NEW;
drop table O2D_DDL_4.O2D_DDL_4_DATATYPES_NEW; 
drop table O2D_DDL_4.O2D_DDL_4_RAWLOBTYPES_NEW;
commit;

truncate table O2D_DDL_4.O2D_DDL_4_NUMBERTYPES;
truncate table O2D_DDL_4.O2D_DDL_4_CHARTYPES;
truncate table O2D_DDL_4.O2D_DDL_4_DATATYPES; 
truncate table O2D_DDL_4.O2D_DDL_4_RAWLOBTYPES;
commit;

