spool spool_check.txt

SELECT COUNT (distinct s_bigint) AS mssql_bounds_types
  FROM ((SELECT s_bigint,S_VARCHAR,S_CHAR,S_NCHAR,S_NVARCHAR,S_DATETIME27,
                S_DATETIME26,S_DATETIME25,S_DATETIME24,S_DATETIME23,S_DATETIME22,
                S_DATETIME21,S_DATETIME20,S_DATETIMEOFFS4,S_DATETIMEOFFS5,S_DATETIMEOFFS6,S_DATETIMEOFFS7,
                S_TIME7,S_DATETIMEOFFS0,S_DATETIMEOFFS1,S_DATETIMEOFFS2,S_DATETIMEOFFS3,S_TIME6,
                S_TIME0,S_TIME1,S_TIME2,S_TIME3,S_TIME4,S_TIME5
           FROM DBDEST_USER.ALL_TYPES_MSSQL_BOUNDS
         MINUS
         SELECT s_bigint,S_VARCHAR,S_CHAR,S_NCHAR,S_NVARCHAR,S_DATETIME27,
                S_DATETIME26,S_DATETIME25,S_DATETIME24,S_DATETIME23,S_DATETIME22,
                S_DATETIME21,S_DATETIME20,S_DATETIMEOFFS4,S_DATETIMEOFFS5,S_DATETIMEOFFS6,S_DATETIMEOFFS7,
                S_TIME7,S_DATETIMEOFFS0,S_DATETIMEOFFS1,S_DATETIMEOFFS2,S_DATETIMEOFFS3,S_TIME6,
                S_TIME0,S_TIME1,S_TIME2,S_TIME3,S_TIME4,S_TIME5
           FROM dbdest_sec_user.ALL_TYPES_MSSQL_BOUNDS)
        UNION ALL
        (SELECT s_bigint,S_VARCHAR,S_CHAR,S_NCHAR,S_NVARCHAR,S_DATETIME27,
                S_DATETIME26,S_DATETIME25,S_DATETIME24,S_DATETIME23,S_DATETIME22,
                S_DATETIME21,S_DATETIME20,S_DATETIMEOFFS4,S_DATETIMEOFFS5,S_DATETIMEOFFS6,S_DATETIMEOFFS7,
                S_TIME7,S_DATETIMEOFFS0,S_DATETIMEOFFS1,S_DATETIMEOFFS2,S_DATETIMEOFFS3,S_TIME6,
                S_TIME0,S_TIME1,S_TIME2,S_TIME3,S_TIME4,S_TIME5
           FROM dbdest_sec_user.ALL_TYPES_MSSQL_BOUNDS
         MINUS
         SELECT s_bigint,S_VARCHAR,S_CHAR,S_NCHAR,S_NVARCHAR,S_DATETIME27,
                S_DATETIME26,S_DATETIME25,S_DATETIME24,S_DATETIME23,S_DATETIME22,
                S_DATETIME21,S_DATETIME20,S_DATETIMEOFFS4,S_DATETIMEOFFS5,S_DATETIMEOFFS6,S_DATETIMEOFFS7,
                S_TIME7,S_DATETIMEOFFS0,S_DATETIMEOFFS1,S_DATETIMEOFFS2,S_DATETIMEOFFS3,S_TIME6,
                S_TIME0,S_TIME1,S_TIME2,S_TIME3,S_TIME4,S_TIME5
           FROM dbdest_user.ALL_TYPES_MSSQL_BOUNDS));

select count(*) as unsync_S_NTEXT1 from dbdest_sec_user.ALL_TYPES_MSSQL_BOUNDS a join 
 dbdest_user.ALL_TYPES_MSSQL_BOUNDS b on A.s_bigint=B.s_bigint
 where DBMS_LOB.compare(a.S_NTEXT1, b.S_NTEXT1) <>0;
 
select count(*) as unsync_S_NTEXT2 from dbdest_sec_user.ALL_TYPES_MSSQL_BOUNDS a join 
 dbdest_user.ALL_TYPES_MSSQL_BOUNDS b on A.s_bigint=B.s_bigint
 where DBMS_LOB.compare(a.S_NTEXT2, b.S_NTEXT2) <>0;
 
select count(*) as unsync_S_TEXT1 from dbdest_sec_user.ALL_TYPES_MSSQL_BOUNDS a join 
 dbdest_user.ALL_TYPES_MSSQL_BOUNDS b on A.s_bigint=B.s_bigint
 where DBMS_LOB.compare(a.S_TEXT1, b.S_TEXT1) <>0; 
 
 select count(*) as unsync_S_VARBINARY from dbdest_sec_user.ALL_TYPES_MSSQL_BOUNDS a join 
 dbdest_user.ALL_TYPES_MSSQL_BOUNDS b on A.s_bigint=B.s_bigint
 where DBMS_LOB.compare(a.S_VARBINARY, b.S_VARBINARY) <>0; 
 
 select count(*) as unsync_S_TEXT2 from dbdest_sec_user.ALL_TYPES_MSSQL_BOUNDS a join 
 dbdest_user.ALL_TYPES_MSSQL_BOUNDS b on A.s_bigint=B.s_bigint
 where DBMS_LOB.compare(a.S_TEXT2, b.S_TEXT2) <>0; 
 
  select count(*) as unsync_S_BINARY from dbdest_sec_user.ALL_TYPES_MSSQL_BOUNDS a join 
 dbdest_user.ALL_TYPES_MSSQL_BOUNDS b on A.s_bigint=B.s_bigint
 where DBMS_LOB.compare(a.S_BINARY, b.S_BINARY) <>0; 
 
spool off
exit