--Simple Create IOT
CREATE TABLE simple_iot (
WORK_DATE   DATE,
EMPLOYEE_NO VARCHAR2(8),
CONSTRAINT pk_simple_iot
PRIMARY KEY (work_date, employee_no))
ORGANIZATION INDEX;
 ALTER TABLE simple_iot ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;

--Index Compressed IOT
CREATE TABLE compressed_iot 
(owner, object_id, object_name,
CONSTRAINT pk_compressed_iot
PRIMARY KEY(owner, object_id, object_name))
ORGANIZATION INDEX
COMPRESS 2 AS
SELECT owner, object_id, object_name
FROM all_objects
WHERE SUBSTR(object_name,1,1) BETWEEN 'A' AND 'W';
 ALTER TABLE compressed_iot ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;

--Complex IOT with Including Clause
CREATE TABLE complex_iot (
WORK_DATE            DATE,
EMPLOYEE_NO          VARCHAR2(8),
SUMMIT_WORK_ORDER_NO VARCHAR2(7),
DASH                 VARCHAR2(2),
CLASS_CODE           VARCHAR2(6),
PAYCODE              VARCHAR2(2),
ASSIGNED_CREW_NUMBER VARCHAR2(5),
TRANSFER_CREW_NUMBER VARCHAR2(5),
REFERENCE_TYPE       VARCHAR2(1),
REFERENCE_NUMBER     VARCHAR2(10),
OVERTIME_CODE        VARCHAR2(1),
SHIFT_DIFFERENTIAL   VARCHAR2(1) NOT NULL,
HOURS                NUMBER(4,2) NOT NULL,
MOD_USER_ID          VARCHAR2(30) DEFAULT USER,
MOD_USER_DATE        DATE,
CONSTRAINT pk_complex_iot
PRIMARY KEY (work_date, employee_no, summit_work_order_no, dash, class_code, paycode, assigned_crew_number, transfer_crew_number, reference_type, reference_number, overtime_code, shift_differential))
ORGANIZATION INDEX
INCLUDING hours
OVERFLOW TABLESPACE SRC;
 ALTER TABLE complex_iot ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;

--Complex IOT with Including Clause And Partitioning
--CREATE SMALLFILE TABLESPACE "IOT_PARTITION_1" DATAFILE '/oravl01/oracle/oradata_10/orcl/partition/iot_partition_1.dbf' 
--SIZE 1m
--LOGGING
--EXTENT 
--MANAGEMENT
--LOCAL SEGMENT SPACE MANAGEMENT AUTO;
--CREATE SMALLFILE TABLESPACE "IOT_PARTITION_2" DATAFILE '/oravl01/oracle/oradata_10/orcl/partition/iot_partition_2.dbf' 
--SIZE 1m
--LOGGING
--EXTENT 
--MANAGEMENT
--LOCAL SEGMENT SPACE MANAGEMENT AUTO;
--CREATE SMALLFILE TABLESPACE "IOT_PARTITION_3" DATAFILE '/oravl01/oracle/oradata_10/orcl/partition/iot_partition_3.dbf' 
--SIZE 1m
--LOGGING
--EXTENT 
--MANAGEMENT
--LOCAL SEGMENT SPACE MANAGEMENT AUTO;
--CREATE SMALLFILE TABLESPACE "IOT_PARTITION_4" DATAFILE '/oravl01/oracle/oradata_10/orcl/partition/iot_partition_4.dbf' 
--SIZE 1m
--LOGGING
--EXTENT 
--MANAGEMENT
--LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLE complex_iot_complex (
WORK_DATE            DATE,
EMPLOYEE_NO          VARCHAR2(8),
SUMMIT_WORK_ORDER_NO VARCHAR2(7),
DASH                 VARCHAR2(2),
CLASS_CODE           VARCHAR2(6),
PAYCODE              VARCHAR2(2),
ASSIGNED_CREW_NUMBER VARCHAR2(5),
TRANSFER_CREW_NUMBER VARCHAR2(5),
REFERENCE_TYPE       VARCHAR2(1),
REFERENCE_NUMBER     VARCHAR2(10),
OVERTIME_CODE        VARCHAR2(1),
SHIFT_DIFFERENTIAL   VARCHAR2(1) NOT NULL,
HOURS                NUMBER(4,2) NOT NULL,
MOD_USER_ID          VARCHAR2(30) DEFAULT USER,
MOD_USER_DATE        DATE,
CONSTRAINT pk_complex_iot_complex
PRIMARY KEY (work_date, employee_no, summit_work_order_no, dash, class_code, paycode, assigned_crew_number, transfer_crew_number, reference_type, reference_number, overtime_code, shift_differential))
ORGANIZATION INDEX
INCLUDING hours
OVERFLOW TABLESPACE SRC
PARTITION BY RANGE (work_date) (
PARTITION yr06 VALUES LESS THAN (TO_DATE('01-JAN-2007', 'DD-MON-YYYY')) TABLESPACE SRC,
PARTITION yr07 VALUES LESS THAN (TO_DATE('01-JAN-2008', 'DD-MON-YYYY')) TABLESPACE SRC,
PARTITION yr08 VALUES LESS THAN (TO_DATE('01-JAN-2009', 'DD-MON-YYYY')) TABLESPACE SRC,
PARTITION yr99 VALUES LESS THAN (MAXVALUE) TABLESPACE SRC);
 ALTER TABLE complex_iot_complex ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;

--DROP TABLESPACE IOT_PARTITION_1 INCLUDING CONTENTS AND DATAFILES;
--DROP TABLESPACE IOT_PARTITION_2 INCLUDING CONTENTS AND DATAFILES;
--DROP TABLESPACE IOT_PARTITION_3 INCLUDING CONTENTS AND DATAFILES;
--DROP TABLESPACE IOT_PARTITION_4 INCLUDING CONTENTS AND DATAFILES;