
/*Generated by Informatica Data Replication Console */
/*Converting DDL from MS SQL Server to ORACLE*/
CREATE TABLE "DBDEST_SEC"."ALL_TYPES_MSSQL"
(S_BIGINT NUMBER(19,0) NOT NULL/*MS SQL Server datatype: BIGINT(19, 0)*/,
S_INT NUMBER(10,0)/*MS SQL Server datatype: INT(10, 0)*/,
S_SMALLINT NUMBER(5,0)/*MS SQL Server datatype: SMALLINT(5, 0)*/,
S_TINYINT NUMBER(3,0)/*MS SQL Server datatype: TINYINT(3, 0)*/,
S_BIT NUMBER(1)/*MS SQL Server datatype: BIT(1, 0)*/,
S_DECIMAL NUMBER(38, 8)/*MS SQL Server datatype: DECIMAL(38, 8)*/,
S_NUMERIC NUMBER(38, 8)/*MS SQL Server datatype: NUMERIC(38, 8)*/,
S_MONEY NUMBER(19,4)/*MS SQL Server datatype: MONEY(19, 4)*/,
S_SMALLMONEY NUMBER(10,4)/*MS SQL Server datatype: SMALLMONEY(10, 4)*/,
S_FLOAT FLOAT/*MS SQL Server datatype: FLOAT(53, 0)*/,
S_DATETIME TIMESTAMP(3)/*MS SQL Server datatype: DATETIME(23, 3)*/,
S_SMALDATETIME TIMESTAMP(0)/*MS SQL Server datatype: SMALLDATETIME(16, 0)*/,
S_VARCHAR VARCHAR2(1000 BYTE)/*MS SQL Server datatype: VARCHAR(0, 0)*/,
S_CHAR CHAR(1000 BYTE)/*MS SQL Server datatype: CHAR(0, 0)*/,
S_NCHAR NCHAR(2000)/*MS SQL Server datatype: NCHAR(0, 0)*/,
S_NVARCHAR NVARCHAR2(2000)/*MS SQL Server datatype: NVARCHAR(0, 0)*/,
S_NVARCHARMAX CLOB/*MS SQL Server datatype: NVARCHAR(0, 0)*/,
S_NTEXT NCLOB/*MS SQL Server datatype: NTEXT(0, 0)*/,
S_BINARY BLOB/*MS SQL Server datatype: BINARY(0, 0)*/,
S_VARBINARY BLOB/*MS SQL Server datatype: VARBINARY(0, 0)*/,
S_VARBINMAX BLOB/*MS SQL Server datatype: VARBINARY(0, 0)*/,
S_IMAGE BLOB/*MS SQL Server datatype: IMAGE(0, 0)*/,
S_DATE DATE/*MS SQL Server datatype: DATE(10, 0)*/,
S_DATETIME2 TIMESTAMP(7)/*MS SQL Server datatype: DATETIME2(27, 7)*/,
S_DATETIMEOFFS TIMESTAMP(7) WITH TIME ZONE/*MS SQL Server datatype: DATETIMEOFFSET(34, 7)*/,
S_TIME TIMESTAMP(7)/*MS SQL Server datatype: TIME(16, 7)*/,
S_REAL FLOAT(23)/*MS SQL Server datatype: REAL(24, 0)*/,
PRIMARY KEY (S_BIGINT)
);

CREATE TABLE "DBDEST_SEC"."ALL_TYPES_MSSQL_LONG"
(S_UIDENTIFY RAW(16)/*MS SQL Server datatype: UNIQUEIDENTIFIER(0, 0)*/,
S_BIGINT NUMBER(19,0) NOT NULL/*MS SQL Server datatype: BIGINT(19, 0)*/,
S_VARCHARMAX CLOB/*MS SQL Server datatype: VARCHAR(0, 0)*/,
S_TEXT CLOB/*MS SQL Server datatype: TEXT(0, 0)*/,
S_XML CLOB/*MS SQL Server datatype: XML(0, 0)*/,
PRIMARY KEY (S_BIGINT)
);


