Alter TABLE tab_number drop
(
  
 INTEGER_COL, 
  DATE_COL, 
-- LONG_COL,
-- FLOAT_COL,
  DECIMAL_COL,
  TIMESTAMP_COL,
-- TIMESTAMP_TZ_COL,
  NCHAR_COL,
  CLOB_COL,
  NCLOB_COL,
  BLOB_COL,
  VARCHAR2_COL,
 NVARCHAR2_COL,
  BIN_DOUBLE_COL,
  BIN_FLOAT_COL,
-- RAW_COL,
  NUMERIC_COL,
--  TIMESTAMP_LTZ_COL,
 CHAR_COL
--  DOUBLE_PRECISION_COL,
--  INTERVAL_DS_COL,
--  INTERVAL_YM_COL
 );
 
 commit;
 
 --Alter TABLE DBSYNC_USER.TAB_NUMBER drop column NCHAR_COL;
 
 Alter TABLE tab_number drop column LONG_COL;