truncate TABLE src.d2o_conflict_2_01 immediate;
truncate TABLE src.d2o_conflict_2_02 immediate;
truncate TABLE src.d2o_conflict_2_03 immediate;
truncate TABLE src.d2o_conflict_2_04 immediate;
truncate TABLE src.d2o_conflict_2_05 immediate;
truncate TABLE src.d2o_conflict_2_06 immediate;
truncate TABLE src.d2o_conflict_2_07 immediate;
truncate TABLE src.d2o_conflict_2_08 immediate;
truncate TABLE src.d2o_conflict_2_09 immediate;
truncate TABLE src.d2o_conflict_2_10 immediate;
truncate TABLE src.d2o_conflict_2_11 immediate;
truncate TABLE src.d2o_conflict_2_12 immediate;
truncate TABLE src.d2o_conflict_2_13 immediate;
truncate TABLE src.d2o_conflict_2_14 immediate;
truncate TABLE src.d2o_conflict_2_15 immediate;
truncate TABLE src.d2o_conflict_2_16 immediate;
truncate TABLE src.d2o_conflict_2_17 immediate;

truncate TABLE conflicts.d2o_conflict_2_01;
truncate TABLE conflicts.d2o_conflict_2_02;
truncate TABLE conflicts.d2o_conflict_2_03;
truncate TABLE conflicts.d2o_conflict_2_04;
truncate TABLE conflicts.d2o_conflict_2_05;
truncate TABLE conflicts.d2o_conflict_2_06;
truncate TABLE conflicts.d2o_conflict_2_07;
truncate TABLE conflicts.d2o_conflict_2_08;
truncate TABLE conflicts.d2o_conflict_2_09;
truncate TABLE conflicts.d2o_conflict_2_10;
truncate TABLE conflicts.d2o_conflict_2_11;
truncate TABLE conflicts.d2o_conflict_2_12;
truncate TABLE conflicts.d2o_conflict_2_13;
truncate TABLE conflicts.d2o_conflict_2_14;
truncate TABLE conflicts.d2o_conflict_2_15;
truncate TABLE conflicts.d2o_conflict_2_16;
truncate TABLE conflicts.d2o_conflict_2_17;
