ALter TABLE [db_to_ora].[testing].[TAB_NUMBER] drop column
	[INTEGER_COL]
	,[DATE_COL]
	,[LONG_COL]
	,[FLOAT_COL]
	,[DECIMAL_COL]
	,[TIMESTAMP_COL]
	,[TIMESTAMP_TZ_COL]
	,[CLOB_COL]
	,[NCLOB_COL]	
	,[BLOB_COL]
	,[VARCHAR2_COL]
	,[NVARCHAR2_COL] 
	,[BIN_DOUBLE_COL]
	,[BIN_FLOAT_COL]
	,[RAW_COL]
	,[NUMERIC_COL]
	,[CHAR_COL]
	,[DOUBLE_PRECISION_COL]
	,[NCHAR_COL]
	,[TIMESTAMP_LTZ_COL];


