--COL RENAME

CREATE TABLE DDL_COL_ALTER
(
Col1 NUMBER,
Col2 VARCHAR(32)
);


ALTER TABLE DDL_COL_ALTER MODIFY (Col1 NUMBER NOT NULL);
ALTER TABLE DDL_COL_ALTER MODIFY (Col2 DATE NOT NULL);
