
/*Generated by Informatica Data Replication Console */
/*Converting DDL from Sybase ASE to ORACLE*/
CREATE TABLE "DST_TEST_USER"."SBS_BASIC_TYPES"
(S_INT NUMBER(10,0) NOT NULL/*Sybase ASE datatype: INT(0, 0)*/,
S_BIT NUMBER(1) NOT NULL/*Sybase ASE datatype: BIT(0, 0)*/,
S_TINYINT NUMBER(3,0)/*Sybase ASE datatype: TINYINT(0, 0)*/,
S_SMALLINT NUMBER(5,0)/*Sybase ASE datatype: SMALLINT(0, 0)*/,
S_USMALLINT NUMBER(5,0)/*Sybase ASE datatype: USMALLINT(0, 0)*/,
S_UINT NUMBER(10,0)/*Sybase ASE datatype: UINT(0, 0)*/,
S_BIGINT NUMBER(19,0)/*Sybase ASE datatype: BIGINT(0, 0)*/,
S_UBIGINT NUMBER(19,0)/*Sybase ASE datatype: UBIGINT(0, 0)*/,
PRIMARY KEY (S_INT)
);


-----------------------------------------------------------------
CREATE TABLE "DST_TEST_USER"."SBS_BINARY_TYPES"
(S_INT NUMBER(10,0) NOT NULL/*Sybase ASE datatype: INT(0, 0)*/,
S_BINARY raw/*Sybase ASE datatype: VARBINARY(0, 0)*/,  ------------BLOB?
S_VARBINARY raw/*Sybase ASE datatype: VARBINARY(0, 0)*/,
S_IMAGE BLOB/*Sybase ASE datatype: IMAGE(0, 0)*/,
PRIMARY KEY (S_INT)
);

----------------------------------------------------------------------
CREATE TABLE "DST_TEST_USER"."SBS_CHARACTER_TYPES"
(S_INT NUMBER(10,0) NOT NULL/*Sybase ASE datatype: INT(0, 0)*/,
S_CHAR nvarchar(100)/*Sybase ASE datatype: NVARCHAR(0, 0)*/,
S_VARCHAR nvarchar(500)/*Sybase ASE datatype: NVARCHAR(0, 0)*/,
S_UNICHAR varchar2(200)/*Sybase ASE datatype: UNIVARCHAR(0, 0)*/,
S_UNIVARCHAR varchar2(1000)/*Sybase ASE datatype: UNIVARCHAR(0, 0)*/,
S_NCHAR nvarchar(100)/*Sybase ASE datatype: NVARCHAR(0, 0)*/,
S_NVARCHAR nvarchar(500)/*Sybase ASE datatype: NVARCHAR(0, 0)*/,
PRIMARY KEY (S_INT)
);

CREATE TABLE "DST_TEST_USER"."SBS_CHARACTER_TYPES_LNG"
(S_INT NUMBER(10,0) NOT NULL/*Sybase ASE datatype: INT(0, 0)*/,
S_TEXT CLOB/*Sybase ASE datatype: TEXT(0, 0)*/,
S_UNITEXT CLOB/*Sybase ASE datatype: UNITEXT(0, 0)*/,
PRIMARY KEY (S_INT)
);

CREATE TABLE "DST_TEST_USER"."SBS_DATETIME_TYPES"
(S_INT NUMBER(10,0) NOT NULL/*Sybase ASE datatype: INT(0, 0)*/,
S_SMALLDATETIME TIMESTAMP(3)/*Sybase ASE datatype: SMALLDATETIME(0, 0)*/,
S_DATETIME TIMESTAMP(6)/*Sybase ASE datatype: DATETIME(0, 0)*/,
S_DATE date/*Sybase ASE datatype: DATE(0, 0)*/,
S_TIME TIMESTAMP(6)/*Sybase ASE datatype: TIME(0, 0)*/,
PRIMARY KEY (S_INT)
);

CREATE TABLE "DST_TEST_USER"."SBS_DECIMAL_TYPES"
(S_INT NUMBER(10,0) NOT NULL/*Sybase ASE datatype: INT(0, 0)*/,
S_NUMERIC NUMBER(38, 8)/*Sybase ASE datatype: NUMERIC(38, 8)*/,
S_DECIMAL NUMBER(38, 8)/*Sybase ASE datatype: DECIMAL(38, 8)*/,
S_FLOAT float(7)/*Sybase ASE datatype: FLOAT(0, 0)*/,
S_DOUBLE float(7)/*Sybase ASE datatype: FLOAT(0, 0)*/,
S_REAL float(23)/*Sybase ASE datatype: REAL(0, 0)*/,
PRIMARY KEY (S_INT)
);

CREATE TABLE "DST_TEST_USER"."SBS_MONEY_TYPES"
(S_INT NUMBER(10,0) NOT NULL/*Sybase ASE datatype: INT(0, 0)*/,
S_SMALLMONEY NUMBER(10,4)/*Sybase ASE datatype: SMALLMONEY(0, 0)*/,
S_MONEY NUMBER(19,4)/*Sybase ASE datatype: MONEY(0, 0)*/,
PRIMARY KEY (S_INT)
);


