ALTER TABLE O2D_DDL_5.O2D_DDL_5_NUMBERTYPES MODIFY S_NUMBER_MAX DEFAULT 28.1584;
ALTER TABLE O2D_DDL_5.O2D_DDL_5_NUMBERTYPES MODIFY S_NUMBER_MID DEFAULT 0.1806;
ALTER TABLE O2D_DDL_5.O2D_DDL_5_NUMBERTYPES MODIFY S_NUMBER_MIN DEFAULT 0.3;
ALTER TABLE O2D_DDL_5.O2D_DDL_5_NUMBERTYPES MODIFY S_INTEGER DEFAULT 2531035149;
ALTER TABLE O2D_DDL_5.O2D_DDL_5_NUMBERTYPES MODIFY S_BINARY_DOUBLE DEFAULT 0.13024826;
ALTER TABLE O2D_DDL_5.O2D_DDL_5_NUMBERTYPES MODIFY S_BINARY_FLOAT DEFAULT 1.22039757E9;
ALTER TABLE O2D_DDL_5.O2D_DDL_5_NUMBERTYPES MODIFY S_DECIMAL_MAX DEFAULT -32.12840254;
ALTER TABLE O2D_DDL_5.O2D_DDL_5_NUMBERTYPES MODIFY S_DECIMAL_MID DEFAULT -0.42134705;
ALTER TABLE O2D_DDL_5.O2D_DDL_5_NUMBERTYPES MODIFY S_DECIMAL_MIN DEFAULT 0.3;
ALTER TABLE O2D_DDL_5.O2D_DDL_5_NUMBERTYPES MODIFY S_DOUBLE_PRECISION_FLOAT_MAX DEFAULT 0.272191589;
ALTER TABLE O2D_DDL_5.O2D_DDL_5_NUMBERTYPES MODIFY S_DOUBLE_PRECISION_FLOAT_MID DEFAULT 6.2314433;
ALTER TABLE O2D_DDL_5.O2D_DDL_5_NUMBERTYPES MODIFY S_DOUBLE_PRECISION_FLOAT_MIN DEFAULT -4;

ALTER TABLE O2D_DDL_5.O2D_DDL_5_CHARTYPES MODIFY S_VARCHAR2_MAX DEFAULT 'T_VARCHAR2_MAX';
ALTER TABLE O2D_DDL_5.O2D_DDL_5_CHARTYPES MODIFY S_VARCHAR2_MID DEFAULT 'WARCHAR2_MID';
ALTER TABLE O2D_DDL_5.O2D_DDL_5_CHARTYPES MODIFY S_VARCHAR2_MIN DEFAULT 'T';
ALTER TABLE O2D_DDL_5.O2D_DDL_5_CHARTYPES MODIFY S_CHAR_MAX DEFAULT 'T_CHAR_MAX';
ALTER TABLE O2D_DDL_5.O2D_DDL_5_CHARTYPES MODIFY S_CHAR_MID DEFAULT 'DHAR_MID';
ALTER TABLE O2D_DDL_5.O2D_DDL_5_CHARTYPES MODIFY S_CHAR_MIN DEFAULT 'T';
ALTER TABLE O2D_DDL_5.O2D_DDL_5_CHARTYPES MODIFY S_NVARCHAR2_MAX DEFAULT 'T_NVARCHAR2_MAX';
ALTER TABLE O2D_DDL_5.O2D_DDL_5_CHARTYPES MODIFY S_NVARCHAR2_MID DEFAULT 'OVARCHAR2_MID';
ALTER TABLE O2D_DDL_5.O2D_DDL_5_CHARTYPES MODIFY S_NVARCHAR2_MIN DEFAULT 'T';
ALTER TABLE O2D_DDL_5.O2D_DDL_5_CHARTYPES MODIFY S_NCHAR_MAX DEFAULT 'T_NCHAR_MAX';
ALTER TABLE O2D_DDL_5.O2D_DDL_5_CHARTYPES MODIFY S_NCHAR_MID DEFAULT 'OCHAR_MID';
ALTER TABLE O2D_DDL_5.O2D_DDL_5_CHARTYPES MODIFY S_NCHAR_MIN DEFAULT 'T';

ALTER TABLE O2D_DDL_5.O2D_DDL_5_DATATYPES MODIFY S_DATE DEFAULT TO_DATE('2012.02.09','yyyy.mm.dd');
ALTER TABLE O2D_DDL_5.O2D_DDL_5_DATATYPES MODIFY S_TIMESTAMP_WITOUT_TZ_MAX DEFAULT TO_TIMESTAMP('2000-03-09 00:04:04.323','YYYY-MM-DD HH24:MI:SS.FF');
ALTER TABLE O2D_DDL_5.O2D_DDL_5_DATATYPES MODIFY S_TIMESTAMP_WITOUT_TZ_MID DEFAULT TO_TIMESTAMP('2009-03-03 00:39:44.330','YYYY-MM-DD HH24:MI:SS.FF');
ALTER TABLE O2D_DDL_5.O2D_DDL_5_DATATYPES MODIFY S_TIMESTAMP_WITOUT_TZ_MIN DEFAULT TO_TIMESTAMP('2010-05-08 00:07:04.000','YYYY-MM-DD HH24:MI:SS.FF');

ALTER TABLE O2D_DDL_5.O2D_DDL_5_RAWLOBTYPES MODIFY S_RAW_MAX DEFAULT hextoraw('33bc');
ALTER TABLE O2D_DDL_5.O2D_DDL_5_RAWLOBTYPES MODIFY S_RAW_MID DEFAULT hextoraw('bf32');
ALTER TABLE O2D_DDL_5.O2D_DDL_5_RAWLOBTYPES MODIFY S_RAW_MIN DEFAULT hextoraw('3A');
ALTER TABLE O2D_DDL_5.O2D_DDL_5_RAWLOBTYPES MODIFY S_BLOB DEFAULT hextoraw('553d7a34');
ALTER TABLE O2D_DDL_5.O2D_DDL_5_RAWLOBTYPES MODIFY S_CLOB DEFAULT hextoraw('733e7a32');
commit;
