CREATE TABLE  O2D_DDL_1.O2D_DDL_1_NUMBERTYPES
(
  S_NUMBER_MAX			NUMBER(38,10),
  S_NUMBER_MID			NUMBER(19,10),
  S_NUMBER_MIN              	NUMBER(1,1),
  S_INTEGER                 	INTEGER,
  S_BINARY_DOUBLE           	BINARY_DOUBLE,
  S_BINARY_FLOAT            	BINARY_FLOAT,
  S_DECIMAL_MAX             	DECIMAL(30,8),
  S_DECIMAL_MID             	DECIMAL(15,8),
  S_DECIMAL_MIN             	DECIMAL(2,1),
  S_DOUBLE_PRECISION_FLOAT_MAX  FLOAT(126),
  S_DOUBLE_PRECISION_FLOAT_MID  FLOAT(63),
  S_DOUBLE_PRECISION_FLOAT_MIN  FLOAT(1),  
  S_PK_FORMAPPING           	INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE  O2D_DDL_1.O2D_DDL_1_CHARTYPES
(
  S_VARCHAR2_MAX       VARCHAR2(4000 BYTE),
  S_VARCHAR2_MID       VARCHAR2(2000 BYTE),
  S_VARCHAR2_MIN       VARCHAR2(1 BYTE),
  S_CHAR_MAX           CHAR(2000 BYTE),
  S_CHAR_MID           CHAR(1000 BYTE),
  S_CHAR_MIN           CHAR(1 BYTE),
  S_NVARCHAR2_MAX      NVARCHAR2(2000),
  S_NVARCHAR2_MID      NVARCHAR2(1000),
  S_NVARCHAR2_MIN      NVARCHAR2(1),
  S_NCHAR_MAX          NCHAR(1000),
  S_NCHAR_MID          NCHAR(500),
  S_NCHAR_MIN          NCHAR(1),
  S_PK_FORMAPPING      INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE  O2D_DDL_1.O2D_DDL_1_DATATYPES
(
  S_DATE                     DATE,
  S_TIMESTAMP_WITOUT_TZ_MAX      TIMESTAMP(9),
  S_TIMESTAMP_WITOUT_TZ_MID      TIMESTAMP(6),
  S_TIMESTAMP_WITOUT_TZ_MIN      TIMESTAMP(0),
  S_PK_FORMAPPING            INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE  O2D_DDL_1.O2D_DDL_1_RAWLOBTYPES
(
  S_RAW_MAX            RAW(2000),
  S_RAW_MID            RAW(1000),
  S_RAW_MIN            RAW(1),
  S_BLOB           BLOB,
  S_CLOB           CLOB,
  S_PK_FORMAPPING  INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE  O2D_DDL_1.O2D_DDL_1_NUMBERTYPES ADD (
  CONSTRAINT O2D_DDL_1_NUMBERTYPES_PK
 PRIMARY KEY
 (S_PK_FORMAPPING));

ALTER TABLE  O2D_DDL_1.O2D_DDL_1_DATATYPES ADD (
  CONSTRAINT O2D_DDL_1_DATATYPES_PK
 PRIMARY KEY
 (S_PK_FORMAPPING));

ALTER TABLE  O2D_DDL_1.O2D_DDL_1_RAWLOBTYPES ADD (
  CONSTRAINT O2D_DDL_1_RAWLOBTYPES_PK
 PRIMARY KEY
 (S_PK_FORMAPPING));

ALTER TABLE  O2D_DDL_1.O2D_DDL_1_CHARTYPES ADD (
  CONSTRAINT O2D_DDL_1_CHARTYPES_PK
 PRIMARY KEY
 (S_PK_FORMAPPING));
