CREATE TABLE O2D_DDL_1.O2D_DDL_1_INDEX_ORGANIZED_PARTITIONING
(
s_id   NUMBER(5), 
s_name VARCHAR2(30), 
s_amount  NUMBER(10), 
s_date    DATE, 
PRIMARY KEY(s_date, s_id)) 
ORGANIZATION INDEX INCLUDING s_id 
OVERFLOW TABLESPACE tabsp_overflow 
PARTITION BY RANGE(s_date)
(PARTITION jan2000 VALUES LESS THAN(TO_DATE('02/01/2000','DD/MM/YYYY'))
 OVERFLOW TABLESPACE p1_overflow, 
 PARTITION feb2000 VALUES LESS THAN(TO_DATE('03/01/2000','DD/MM/YYYY'))
 OVERFLOW TABLESPACE p2_overflow, 
 PARTITION mar2000 VALUES LESS THAN(TO_DATE('04/01/2000','DD/MM/YYYY'))
 OVERFLOW TABLESPACE p3_overflow, 
 PARTITION apr2000 VALUES LESS THAN(TO_DATE('05/01/2000','DD/MM/YYYY'))
 OVERFLOW TABLESPACE p4_overflow);
