CREATE TABLE O2D_DDL_1.O2D_DDL_1_IOT
(
  COL1  DATE,
  COL2  TIMESTAMP(6),
  COL3  CHAR(200 BYTE),
  COL4 	INTEGER,
  SUPPLEMENTAL LOG GROUP O2D_DDL_1_IOT_DBSYNC1 (COL1) ALWAYS, 
  CONSTRAINT O2D_DDL_1_SYS_IOT_TOP_108913
PRIMARY KEY
(COL4)
)
ORGANIZATION INDEX
LOGGING
NOPARALLEL
MONITORING;
