CREATE TABLE O2D_DDL_1.O2D_DDL_1_IOT_OVERFLOW
(
  COL1   TIMESTAMP(3),
  COL3   NUMBER(14),
  COL5   RAW(200),
  COL10  RAW(200),
  SUPPLEMENTAL LOG GROUP O2D_DDL_1_IOT_OVERFLOW_DBSYNC1 (COL5,COL1) ALWAYS, 
  CONSTRAINT O2D_DDL_1_SYS_IOT_TOP_108739
PRIMARY KEY
(COL1, COL5)
)
ORGANIZATION INDEX
LOGGING
INCLUDING COL10
OVERFLOW
MONITORING
NOPARALLEL
MONITORING;
