--oracle
--DROP USER O2D_DDL_2 CASCADE;
CREATE USER O2D_DDL_2 IDENTIFIED BY O2D_DDL_2;
GRANT CONNECT, RESOURCE TO O2D_DDL_2;

--db2
CONNECT TO SOURCE;
CREATE SCHEMA O2D_DDL_2 AUTHORIZATION ATF;
CONNECT RESET;
