CREATE TABLE  O2D_DDL_2.O2D_DDL_2_NUMBERTYPES
(
  S_NUMBER_MAX			NUMBER(38,10),
  S_NUMBER_MID			NUMBER(19,10),
  S_NUMBER_MIN              	NUMBER(1,1),
  S_INTEGER                 	INTEGER,
  S_BINARY_DOUBLE           	BINARY_DOUBLE,
  S_BINARY_FLOAT            	BINARY_FLOAT,
  S_DECIMAL_MAX             	DECIMAL(30,8),
  S_DECIMAL_MID             	DECIMAL(15,8),
  S_DECIMAL_MIN             	DECIMAL(2,1),
  S_DOUBLE_PRECISION_FLOAT_MAX  FLOAT(126),
  S_DOUBLE_PRECISION_FLOAT_MID  FLOAT(63),
  S_DOUBLE_PRECISION_FLOAT_MIN  FLOAT(1),  
  S_PK_FORMAPPING           	INTEGER,
  CONSTRAINT O2D_DDL_2_1_PK PRIMARY KEY (S_PK_FORMAPPING)
);

CREATE TABLE  O2D_DDL_2.O2D_DDL_2_CHARTYPES
(
  S_VARCHAR2_MAX       VARCHAR2(4000 BYTE),
  S_VARCHAR2_MID       VARCHAR2(2000 BYTE),
  S_VARCHAR2_MIN       VARCHAR2(1 BYTE),
  S_CHAR_MAX           CHAR(2000 BYTE),
  S_CHAR_MID           CHAR(1000 BYTE),
  S_CHAR_MIN           CHAR(1 BYTE),
  S_NVARCHAR2_MAX      NVARCHAR2(2000),
  S_NVARCHAR2_MID      NVARCHAR2(1000),
  S_NVARCHAR2_MIN      NVARCHAR2(1),
  S_NCHAR_MAX          NCHAR(1000),
  S_NCHAR_MID          NCHAR(500),
  S_NCHAR_MIN          NCHAR(1),
  S_PK_FORMAPPING      INTEGER,
  CONSTRAINT O2D_DDL_2_2_PK PRIMARY KEY (S_PK_FORMAPPING)
);

CREATE TABLE  O2D_DDL_2.O2D_DDL_2_DATATYPES
(
  S_DATE                     DATE,
  S_TIMESTAMP_WITOUT_TZ_MAX      TIMESTAMP(9),
  S_TIMESTAMP_WITOUT_TZ_MID      TIMESTAMP(6),
  S_TIMESTAMP_WITOUT_TZ_MIN      TIMESTAMP(0),
  S_PK_FORMAPPING            INTEGER,
  CONSTRAINT O2D_DDL_2_3_PK PRIMARY KEY (S_PK_FORMAPPING)
);

CREATE TABLE  O2D_DDL_2.O2D_DDL_2_RAWLOBTYPES
(
  S_RAW_MAX            RAW(2000),
  S_RAW_MID            RAW(1000),
  S_RAW_MIN            RAW(1),
  S_BLOB           BLOB,
  S_CLOB           CLOB,
  S_PK_FORMAPPING  INTEGER,
  CONSTRAINT O2D_DDL_2_4_PK PRIMARY KEY (S_PK_FORMAPPING)
);
commit;

alter table O2D_DDL_2.O2D_DDL_2_NUMBERTYPES ADD SUPPLEMENTAL LOG GROUP O2D_DDL_2_1_LG (S_PK_FORMAPPING) ALWAYS;
alter table O2D_DDL_2.O2D_DDL_2_CHARTYPES ADD SUPPLEMENTAL LOG GROUP O2D_DDL_2_2_LG (S_PK_FORMAPPING) ALWAYS;
alter table O2D_DDL_2.O2D_DDL_2_DATATYPES ADD SUPPLEMENTAL LOG GROUP O2D_DDL_2_3_LG (S_PK_FORMAPPING) ALWAYS;
alter table O2D_DDL_2.O2D_DDL_2_RAWLOBTYPES ADD SUPPLEMENTAL LOG GROUP O2D_DDL_2_4_LG (S_PK_FORMAPPING) ALWAYS;
