ALTER TABLE O2D_DDL_2.O2D_DDL_2_NUMBERTYPES DROP (S_NUMBER_MAX, S_BINARY_FLOAT, S_DOUBLE_PRECISION_FLOAT_MIN);
ALTER TABLE O2D_DDL_2.O2D_DDL_2_CHARTYPES DROP (S_VARCHAR2_MAX, S_NVARCHAR2_MAX, S_NCHAR_MIN);
ALTER TABLE O2D_DDL_2.O2D_DDL_2_DATATYPES DROP (S_DATE, S_TIMESTAMP_WITOUT_TZ_MID, S_TIMESTAMP_WITOUT_TZ_MIN);
ALTER TABLE O2D_DDL_2.O2D_DDL_2_RAWLOBTYPES DROP (S_RAW_MAX, S_RAW_MIN, S_CLOB);
commit;
