truncate TABLE src.d2o_conflict_3_01 immediate;
truncate TABLE src.d2o_conflict_3_02 immediate;
truncate TABLE src.d2o_conflict_3_03 immediate;
truncate TABLE src.d2o_conflict_3_04 immediate;
truncate TABLE src.d2o_conflict_3_05 immediate;
truncate TABLE src.d2o_conflict_3_06 immediate;
truncate TABLE src.d2o_conflict_3_07 immediate;
truncate TABLE src.d2o_conflict_3_08 immediate;
truncate TABLE src.d2o_conflict_3_09 immediate;
truncate TABLE src.d2o_conflict_3_10 immediate;
truncate TABLE src.d2o_conflict_3_11 immediate;
truncate TABLE src.d2o_conflict_3_12 immediate;
truncate TABLE src.d2o_conflict_3_13 immediate;
truncate TABLE src.d2o_conflict_3_14 immediate;
truncate TABLE src.d2o_conflict_3_15 immediate;
truncate TABLE src.d2o_conflict_3_16 immediate;
truncate TABLE src.d2o_conflict_3_17 immediate;

truncate TABLE conflicts.d2o_conflict_3_01;
truncate TABLE conflicts.d2o_conflict_3_02;
truncate TABLE conflicts.d2o_conflict_3_03;
truncate TABLE conflicts.d2o_conflict_3_04;
truncate TABLE conflicts.d2o_conflict_3_05;
truncate TABLE conflicts.d2o_conflict_3_06;
truncate TABLE conflicts.d2o_conflict_3_07;
truncate TABLE conflicts.d2o_conflict_3_08;
truncate TABLE conflicts.d2o_conflict_3_09;
truncate TABLE conflicts.d2o_conflict_3_10;
truncate TABLE conflicts.d2o_conflict_3_11;
truncate TABLE conflicts.d2o_conflict_3_12;
truncate TABLE conflicts.d2o_conflict_3_13;
truncate TABLE conflicts.d2o_conflict_3_14;
truncate TABLE conflicts.d2o_conflict_3_15;
truncate TABLE conflicts.d2o_conflict_3_16;
truncate TABLE conflicts.d2o_conflict_3_17;
