GRANT CREATE ANY VIEW TO DDLS;

GRANT CONNECT TO DDLS;
GRANT RESOURCE TO DDLS;
GRANT UNLIMITED TABLESPACE TO DDLS;
GRANT EXECUTE on DBMS_FLASHBACK TO DDLS;
GRANT SELECT ANY TABLE TO DDLS;
GRANT SELECT ANY DICTIONARY TO DDLS;
GRANT ALTER SESSION TO DDLS;

GRANT CONNECT TO DDLS;
GRANT RESOURCE TO DDLS;
GRANT SELECT ANY TABLE TO DDLS;
GRANT SELECT ANY DICTIONARY TO DDLS;
GRANT ALTER SESSION TO DDLS;

GRANT INSERT ANY TABLE TO DDLS;
GRANT UPDATE ANY TABLE TO DDLS;
GRANT DELETE ANY TABLE TO DDLS;

GRANT CREATE DATABASE LINK TO DDLS;
GRANT ALTER ANY TABLE TO DDLS;

GRANT LOCK ANY TABLE TO DDLS;
