./changes.sh > 1.out & 
./changes.sh > 2.out &
./changes.sh > 3.out &
./changes.sh > 4.out &
./changes.sh > 5.out &
./changes.sh > 6.out &
./changes.sh > 7.out &
./changes.sh > 8.out &
./changes.sh > 9.out &
./changes.sh > 10.out &
./changes.sh > 11.out &
./changes.sh > 12.out &
./changes.sh > 13.out &
./changes.sh > 14.out &
./changes.sh > 15.out &
./changes.sh > 16.out &
./changes.sh > 17.out &
./changes.sh > 18.out &
./changes.sh > 19.out &
./changes.sh > 20.out &