--oracle
--DROP USER O2D_DDL_5 CASCADE;
CREATE USER O2D_DDL_5 IDENTIFIED BY O2D_DDL_5;
GRANT CONNECT, RESOURCE TO O2D_DDL_5;

--db2
CONNECT TO SOURCE;
CREATE SCHEMA O2D_DDL_5 AUTHORIZATION ATF;
CONNECT RESET;
