CREATE TABLE O2D_DDL_5.O2D_DDL_5_NUMBERTYPES_NEW AS (SELECT * FROM O2D_DDL_5.O2D_DDL_5_NUMBERTYPES);
CREATE TABLE O2D_DDL_5.O2D_DDL_5_CHARTYPES_NEW AS (SELECT * FROM O2D_DDL_5.O2D_DDL_5_CHARTYPES);
CREATE TABLE O2D_DDL_5.O2D_DDL_5_DATATYPES_NEW AS (SELECT * FROM O2D_DDL_5.O2D_DDL_5_DATATYPES);
CREATE TABLE O2D_DDL_5.O2D_DDL_5_RAWLOBTYPES_NEW AS (SELECT * FROM O2D_DDL_5.O2D_DDL_5_RAWLOBTYPES);
commit;
