truncate TABLE src.d2o_conflict_1_01 immediate;
truncate TABLE src.d2o_conflict_1_02 immediate;
truncate TABLE src.d2o_conflict_1_03 immediate;
truncate TABLE src.d2o_conflict_1_04 immediate;
truncate TABLE src.d2o_conflict_1_05 immediate;
truncate TABLE src.d2o_conflict_1_06 immediate;
truncate TABLE src.d2o_conflict_1_07 immediate;
truncate TABLE src.d2o_conflict_1_08 immediate;
truncate TABLE src.d2o_conflict_1_09 immediate;
truncate TABLE src.d2o_conflict_1_10 immediate;
truncate TABLE src.d2o_conflict_1_11 immediate;
truncate TABLE src.d2o_conflict_1_12 immediate;
truncate TABLE src.d2o_conflict_1_13 immediate;
truncate TABLE src.d2o_conflict_1_14 immediate;
truncate TABLE src.d2o_conflict_1_15 immediate;
truncate TABLE src.d2o_conflict_1_16 immediate;
truncate TABLE src.d2o_conflict_1_17 immediate;

truncate TABLE conflicts.d2o_conflict_1_01;
truncate TABLE conflicts.d2o_conflict_1_02;
truncate TABLE conflicts.d2o_conflict_1_03;
truncate TABLE conflicts.d2o_conflict_1_04;
truncate TABLE conflicts.d2o_conflict_1_05;
truncate TABLE conflicts.d2o_conflict_1_06;
truncate TABLE conflicts.d2o_conflict_1_07;
truncate TABLE conflicts.d2o_conflict_1_08;
truncate TABLE conflicts.d2o_conflict_1_09;
truncate TABLE conflicts.d2o_conflict_1_10;
truncate TABLE conflicts.d2o_conflict_1_11;
truncate TABLE conflicts.d2o_conflict_1_12;
truncate TABLE conflicts.d2o_conflict_1_13;
truncate TABLE conflicts.d2o_conflict_1_14;
truncate TABLE conflicts.d2o_conflict_1_15;
truncate TABLE conflicts.d2o_conflict_1_16;
truncate TABLE conflicts.d2o_conflict_1_17;
